from django.test import TestCase
from doctors.models import Doctor, Specialization, TimeSlot
from datetime import date, time


class SpecializationModelTest(TestCase):
    def setUp(self):
        self.spec = Specialization.objects.create(
            name='Терапевт',
        )

    def test_spec_creation(self):
        self.assertEqual(self.spec.name, 'Терапевт')

    def test_spec_slug_autogenerated(self):
        """Slug генерируется автоматически"""
        self.assertIsNotNone(self.spec.slug)
        self.assertEqual(self.spec.slug, 'terapevt')

    def test_spec_str(self):
        self.assertEqual(str(self.spec), 'Терапевт')


class DoctorModelTest(TestCase):
    def setUp(self):
        self.spec = Specialization.objects.create(name='Терапевт')
        self.doctor = Doctor.objects.create(
            last_name='Иванов',
            first_name='Иван',
            middle_name='Иванович',
            specialization=self.spec,
            experience=10,
            education='МГМУ',
            bio='Опытный врач',
            email='doctor@example.com',
        )

    def test_doctor_creation(self):
        self.assertEqual(self.doctor.last_name, 'Иванов')
        self.assertEqual(self.doctor.experience, 10)
        self.assertTrue(self.doctor.is_active)

    def test_doctor_full_name(self):
        self.assertEqual(
            self.doctor.full_name,
            'Иванов Иван Иванович'
        )

    def test_doctor_str(self):
        self.assertIn('Иванов', str(self.doctor))


class TimeSlotModelTest(TestCase):
    def setUp(self):
        self.spec = Specialization.objects.create(name='Терапевт')
        self.doctor = Doctor.objects.create(
            last_name='Иванов',
            first_name='Иван',
            specialization=self.spec,
            experience=10,
            education='МГМУ',
            bio='Опытный врач',
        )
        self.slot = TimeSlot.objects.create(
            doctor=self.doctor,
            date=date(2026, 12, 1),
            time=time(10, 0),
            is_available=True,
        )

    def test_slot_creation(self):
        self.assertEqual(self.slot.doctor, self.doctor)
        self.assertEqual(self.slot.date, date(2026, 12, 1))
        self.assertEqual(self.slot.time, time(10, 0))
        self.assertTrue(self.slot.is_available)

    def test_slot_str(self):
        self.assertIn('Иванов', str(self.slot))
        self.assertIn('10:00', str(self.slot))

    def test_slot_is_booked_false(self):
        """Слот не занят изначально"""
        self.assertFalse(self.slot.is_booked())
