# Generated by Django 5.0.6 on 2026-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание отправлено'),
        ),
    ]
