# Generated by Django 5.0.6 on 2026-09-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание исследования')),
                ('conclusion', models.TextField(verbose_name='Заключение')),
                ('file', models.FileField(blank=True, null=True, upload_to='results/', verbose_name='Файл результата (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='appointments.appointment', verbose_name='Запись на приём')),
            ],
            options={
                'verbose_name': 'Результат диагностики',
                'verbose_name_plural': 'Результаты диагностики',
                'ordering': ['-created_at'],
            },
        ),
    ]
