# Generated by Django 5.0.6 on 2026-09-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
