# Generated by Django 5.0.6 on 2026-09-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало приёма')),
                ('end_time', models.TimeField(verbose_name='Конец приёма')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва')),
                ('slot_duration', models.IntegerField(default=30, verbose_name='Длительность слота (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Рабочий график',
                'verbose_name_plural': 'Рабочие графики',
                'ordering': ['doctor', 'weekday'],
                'unique_together': {('doctor', 'weekday')},
            },
        ),
    ]
