# Generated by Django 5.0.6 on 2026-09-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно для записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctors.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Доступное время',
                'verbose_name_plural': 'Доступное время',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['doctor', 'date', 'is_available'], name='doctors_tim_doctor__7be654_idx')],
                'unique_together': {('doctor', 'date', 'time')},
            },
        ),
    ]
